GET http://localhost:3000/api/users/

###
GET http://localhost:3000/api/users/655cc319ce27273be6469ce0

###
GET http://localhost:3000/api/texts/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjU3YWY4NjhkMjFlZDdhZTYxMTYwODE1IiwidXNlcl9yb2xlIjoicmVndWxhciIsImlhdCI6MTcwMjU1Nzg1NiwiZXhwIjoxNzAyNjQ0MjU2fQ.5yYo4xW5X2rq4wt7gcnjx4lQ0tW4I30k0BkHv-YZvaY
###
GET http://localhost:3000/api/texts/655e51abbb919350ae6a83f2

###

POST http://localhost:3000/api/texts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjU3YWY4NjhkMjFlZDdhZTYxMTYwODE1IiwidXNlcl9yb2xlIjoicmVndWxhciIsImlhdCI6MTcwMjU1Nzg1NiwiZXhwIjoxNzAyNjQ0MjU2fQ.5yYo4xW5X2rq4wt7gcnjx4lQ0tW4I30k0BkHv-YZvaY
Content-Type: application/json

{
  "title": "Titulo3",
  "creator": {
    "_id": "655cc319ce27273be6469ce0"
  },
  "description": "Description3",
  "content": "Content3",
  "likes": 0,
  "comments": [
    {
      "user": {
        "_id": "655cc319ce27273be6469ce0"
      },
      "comment": "Comment1"
    }
  ],
  "explicit": false
}

###

PUT http://localhost:3000/api/texts/655e51abbb919350ae6a83f2
Content-Type: application/json

{
  "content": "Content1 and more content"
 
}

###
DELETE http://localhost:3000/api/texts/6560d66ecc33b5ced349d474

###

POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "name": "user2",
  "password": "123456",
  "email": "algo2@mail.com",
  "description": "Description2"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "algo2@mail.com",
  "password": "123456"
}