name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm run ins --no-optional --no-audit --no-fund
      - name: Linter
        run: cd WRITEitALL/appBack && npm run lint
      - name: Test and cover
        env:
          MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
          SECRET: ${{ secrets.SECRET }}
        run: cd WRITEitALL/appBack && npm run test
      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        uses: coverallsapp/github-action@v2
      - name: Build
        run: npm run build
      