name: Deployment Pipeline

on:
  push:
    branches:
      - WiA

jobs: 
  deplooy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm run install
      - name: Linter
        run: cd WRITEitALL/appBack && npm run lint