name: Deployment Pipeline

on:
  push:
    branches:
      - WiA

jobs: 
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm run install --no-optional --no-audit --no-fund
      - name: Linter
        run: cd WRITEitALL/appBack && npm run lint
      - name: Test
        env:
          MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: cd WRITEitALL/appBack && npm run test