name: Test BackEnd

on:
  push:
    branches:
      - WiA
jobs:
  tests:
    runs-on: ubuntu/latest
    steps:
      - name: Instalar las dependencias
        run: |
          cd WRITEitALL/appBack | npm i
